name: RedstoneChips
main: org.tal.redstonechips.RedstoneChips
version: 0.5
commands:
  redchips-active:
    description: Lists active redstone circuits.
    usage: /<command>
  redchips-classes:
    description: Lists installed circuit classes.
    usage: /<command>
  redchips-prefs:
    description: View or change plugin preferences. Enter with no arguments to get a full list.

