name: RedstoneChips
main: org.tal.redstonechips.RedstoneChips
version: 0.77
author: eisental
description: Core plugin for integrated redstone circuits 
website: eisental.github.com/RedstoneChips
commands:
  redchips-active:
    description: Lists active redstone circuits.
    usage: /<command>
  redchips-classes:
    description: Lists installed circuit classes.
    usage: /<command>
  redchips-prefs:
    description: View or change plugin preferences. Enter with no arguments to get a full list.
  redchips-debug:
    description: Point towards a circuit block and enter this command to receive debug messages from the circuit. To stop debugging
                 the circuit, use /redchips-debug off.
    usage: /<command> [on | off]
  redchips-pin:
    description: Point at an input or output block (where actual redstone current flows), to get information about the pin.
  redchips-destroy:
    description: Destroys a circuit and turns all of its blocks into air. Point at a block of the circuit you wish to destroy and enter
                 the command.
  redchips-deactivate:
    description: Destroys a circuit w/o removing its blocks. Point at a block of the circuit or enter the circuit's id number as an argument.
