name: RedstoneChips
main: org.tal.redstonechips.RedstoneChips
version: 0.4
commands:
  redchips-active:
    description: Lists active redstone circuits.
    usage: /<command>
  redchips-classes:
    description: Lists installed circuit classes.
    usage: /<command>
