name: RedstoneChips
main: org.tal.redstonechips.RedstoneChips
version: 0.8
author: eisental
description: Core plugin for integrated redstone circuits 
website: eisental.github.com/RedstoneChips
commands:
  rc-list:
    description: Lists active redstone circuits.
    usage: /<command>
  rc-classes:
    description: Lists installed circuit classes.
    usage: /<command>
  rc-prefs:
    description: View or change plugin preferences. Enter with no arguments to get a full list.
  rc-debug:
    description: Point towards a circuit block and enter this command to receive debug messages from the circuit. To stop debugging
                 the circuit, use /redchips-debug off.
    usage: /<command> [on | off]
  rc-pin:
    description: Point at an input or output block (where actual redstone current flows), to get information about the pin.
  rc-destroy:
    description: Destroys a circuit and turns all of its blocks into air. Point at a block of the circuit you wish to destroy and enter
                 the command.
  rc-break:
    description: Deactivates a circuit w/o removing its blocks. Point at a block of the circuit or enter the circuit's id number as an argument.
  rc-type:
    description: Used for typing text or numbers into the circuit. Used by terminal and print for ex.
    usage: /<command> <data>
  rc-reset:
    description: Reactivates a circuit, applying any changes made to the sign with sign edit commands.
    usage: /<command>
  rc-channels:
    description: Lists currently used wireless broadcast channels.
    usage: /<command>
  rc-info:
    description: Sends an info message to the command sender about the trageted circuit. Point at a block of the circuit you wish to get info about.
    usage: /<command>


