name: RedstoneChips
main: org.tal.redstonechips.RedstoneChips
version: 0.86
author: eisental
description: Core plugin for integrated redstone circuits 
website: eisental.github.com/RedstoneChips
commands:
  rc-list:
    description: Prints a list of active chips including their id numbers and locations.
    usage: /<command>
  rc-classes:
    description: Prints a list of installed circuit classes.
    usage: /<command>
  rc-prefs:
    description: Allows to see and change the plugin's preferences. Use the command with no arguments to list all preferences values.
      To change a specific value use /rc-prefs <pref key> <new value>.
  rc-debug:
    description: Registers the executing player to receive debug messages from a chip. Use by either pointing towards the circuit you wish
      to debug or by using /rc-debug <chip id> if you have admin priviliges. To stop receiving debug messages from the chip use the same command again or use /rc-debug off or /rc-debug <chip id> off. To stop receiving debug messages from all circuits use /rc-debug alloff
  rc-pin:
    description: Prints information about a chip pin - it's pin number, type and current state. Point towards an output lever or input redstone
      source to use.
  rc-destroy:
    description: Destroys a circuit and turns all of its blocks into air. Point at a block of the circuit you wish to destroy and enter
                 the command. This command is disabled by default. To enable it use /rc-prefs enableDestroyCommand true.
  rc-break:
    description: Deactivates a circuit without removing its blocks. Point at a block of the circuit or enter the chip's id number as an argument if you have admin priviliges.
  rc-type:
    description: Used for sending text or numbers to supporting circuits. Check the relevant circuit documentation for more information.
  rc-reset:
    description: Reactivates a circuit, applying any changes made to the sign with sign edit commands. Use by pointing towards the circuit or by using
      the chip's id number as an argument if you have admin priviliges.
  rc-channels:
    description: Prints a list of currently used wireless broadcast channels.
  rc-info:
    description: Prints a lot of useful information about a chip. Point at a block of the chip you wish to get info about or use the chip's id number as an argument.
  rc-save:
    description: Saves all circuit data to file. Should not be used unless there's a problem with the automatic data save.
  rc-load:
    description: Reloads circuit data from file. Will reset any changes since last save. 
  rc-help:
    description: Prints a list or description of all RedstoneChips commands. Use /rc-help <command name> to get help about a specific command.



